spring:
  datasource:
    url: jdbc:pgsql://localhost:5432/pc_builder
    username: tuguzT
    driver-class-name: com.impossibl.postgres.jdbc.PGDriver

logging:
  level:
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    org.jetbrains.exposed.spring.SpringTransactionManager: DEBUG
